// plugins/texteffects.js — Ephoto360 text effect commands
// All 18 effects ported to Queen Kylie V1 format using mumaker
'use strict';

const { cmd } = require('../command');
const mumaker = require('mumaker');
const config = require('../config');

// Map of command name -> ephoto360 URL
const EFFECTS = {
  '1917':       'https://en.ephoto360.com/1917-style-text-effect-523.html',
  'arena':      'https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html',
  'blackpink':  'https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html',
  'devil':      'https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html',
  'fire':       'https://en.ephoto360.com/flame-lettering-effect-372.html',
  'glitch':     'https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html',
  'hacker':     'https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html',
  'ice':        'https://en.ephoto360.com/ice-text-effect-online-101.html',
  'impressive': 'https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html',
  'leaves':     'https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html',
  'light':      'https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html',
  'matrix':     'https://en.ephoto360.com/matrix-text-effect-154.html',
  'metallic':   'https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html',
  'neon':       'https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html',
  'purple':     'https://en.ephoto360.com/purple-text-effect-online-100.html',
  'sand':       'https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html',
  'snow':       'https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html',
  'thunder':    'https://en.ephoto360.com/thunder-text-effect-online-97.html',
};

// Register a cmd() for each effect
for (const [name, url] of Object.entries(EFFECTS)) {
  cmd({
    pattern: name,
    desc: `Generate a ${name} style text effect image.`,
    category: 'texteffects',
    react: '🎨',
    filename: __filename
  }, async (conn, mek, m, { q, reply }) => {
    const text = q && q.trim();
    if (!text) return reply(`✏️ Please provide the text you want styled.\nExample: *${config.PREFIX || ':'}${name} YourName*`);

    await reply('⏳ Generating your image, please wait...');

    try {
      const result = await mumaker.ephoto(url, text);
      if (!result || !result.image) throw new Error('No image returned from the API.');

      await conn.sendMessage(m.chat, {
        image: { url: result.image },
        caption: `✨ *${name.toUpperCase()} Effect*\n_Generated by ${config.BOT_NAME || 'QUEEN-KYLIE-V1'}_`
      }, { quoted: mek });

    } catch (e) {
      console.error(`[texteffects:${name}]`, e.message);
      await reply(`❌ Failed to generate the *${name}* effect. The site may be temporarily unavailable, try again in a moment.`);
    }
  });
}
